// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"leegoo/internal/biz"
	"leegoo/internal/conf"
	"leegoo/internal/data"
	"leegoo/internal/server"
	"leegoo/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client, err := data.NewOssClient(confData)
	if err != nil {
		return nil, nil, err
	}
	ossBuckets := data.NewOssBuckets(client)
	dataData, cleanup, err := data.NewData(confData, ossBuckets, logger)
	if err != nil {
		return nil, nil, err
	}
	kvData := data.NewKvData(dataData)
	kvService := service.NewKvService(kvData)
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	ossData := data.NewOssData(dataData)
	ossService := service.NewOssService(ossData)
	grpcServer := server.NewGRPCServer(confServer, kvService, greeterService, ossService, logger)
	httpServer := server.NewHTTPServer(confServer, kvService, greeterService, ossService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
