// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: api/oss/v1/oss.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Oss_GetUrl_FullMethodName  = "/api.oss.v1.Oss/GetUrl"
	Oss_Delete_FullMethodName  = "/api.oss.v1.Oss/Delete"
	Oss_Restore_FullMethodName = "/api.oss.v1.Oss/Restore"
)

// OssClient is the client API for Oss service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OssClient interface {
	GetUrl(ctx context.Context, in *OssRequest, opts ...grpc.CallOption) (*OssReply, error)
	Delete(ctx context.Context, in *OssRequest, opts ...grpc.CallOption) (*OssReply, error)
	Restore(ctx context.Context, in *OssRequest, opts ...grpc.CallOption) (*OssReply, error)
}

type ossClient struct {
	cc grpc.ClientConnInterface
}

func NewOssClient(cc grpc.ClientConnInterface) OssClient {
	return &ossClient{cc}
}

func (c *ossClient) GetUrl(ctx context.Context, in *OssRequest, opts ...grpc.CallOption) (*OssReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OssReply)
	err := c.cc.Invoke(ctx, Oss_GetUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ossClient) Delete(ctx context.Context, in *OssRequest, opts ...grpc.CallOption) (*OssReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OssReply)
	err := c.cc.Invoke(ctx, Oss_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ossClient) Restore(ctx context.Context, in *OssRequest, opts ...grpc.CallOption) (*OssReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OssReply)
	err := c.cc.Invoke(ctx, Oss_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OssServer is the server API for Oss service.
// All implementations must embed UnimplementedOssServer
// for forward compatibility
type OssServer interface {
	GetUrl(context.Context, *OssRequest) (*OssReply, error)
	Delete(context.Context, *OssRequest) (*OssReply, error)
	Restore(context.Context, *OssRequest) (*OssReply, error)
	mustEmbedUnimplementedOssServer()
}

// UnimplementedOssServer must be embedded to have forward compatible implementations.
type UnimplementedOssServer struct {
}

func (UnimplementedOssServer) GetUrl(context.Context, *OssRequest) (*OssReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUrl not implemented")
}
func (UnimplementedOssServer) Delete(context.Context, *OssRequest) (*OssReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedOssServer) Restore(context.Context, *OssRequest) (*OssReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedOssServer) mustEmbedUnimplementedOssServer() {}

// UnsafeOssServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OssServer will
// result in compilation errors.
type UnsafeOssServer interface {
	mustEmbedUnimplementedOssServer()
}

func RegisterOssServer(s grpc.ServiceRegistrar, srv OssServer) {
	s.RegisterService(&Oss_ServiceDesc, srv)
}

func _Oss_GetUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OssRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OssServer).GetUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oss_GetUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OssServer).GetUrl(ctx, req.(*OssRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oss_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OssRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OssServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oss_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OssServer).Delete(ctx, req.(*OssRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oss_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OssRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OssServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oss_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OssServer).Restore(ctx, req.(*OssRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Oss_ServiceDesc is the grpc.ServiceDesc for Oss service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Oss_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.oss.v1.Oss",
	HandlerType: (*OssServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUrl",
			Handler:    _Oss_GetUrl_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Oss_Delete_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _Oss_Restore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/oss/v1/oss.proto",
}
